[17:11:40.164] Yuebon.AspNetCore.Mvc.Filter.ExceptionHandlingAttribute T76 系统警告信息
Yuebon.AspNetCore.Common.MyApiException: Exception of type 'Yuebon.AspNetCore.Common.MyApiException' was thrown.
   at Yuebon.AspNetCore.Mvc.TokenProvider.ValidateToken(String token) in D:\netcorespace\YueGroup\src\Yuebon.AspNetCore\Mvc\TokenProvider.cs:line 100
   at Yuebon.AspNetCore.Controllers.ApiController.CheckToken() in D:\netcorespace\YueGroup\src\Yuebon.AspNetCore\Mvc\ApiController.cs:line 61
   at Yuebon.WebApi.Areas.Security.Controllers.AppController.GetById(String id) in D:\netcorespace\YueGroup\src\Yuebon.WebApi\Areas\Security\Controllers\AppController.cs:line 44
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[17:12:17.938] Yuebon.AspNetCore.Mvc.Filter.ExceptionHandlingAttribute T72 系统警告信息
Yuebon.AspNetCore.Common.MyApiException: Exception of type 'Yuebon.AspNetCore.Common.MyApiException' was thrown.
   at Yuebon.AspNetCore.Mvc.TokenProvider.ValidateToken(String token) in D:\netcorespace\YueGroup\src\Yuebon.AspNetCore\Mvc\TokenProvider.cs:line 100
   at Yuebon.AspNetCore.Controllers.ApiController.CheckToken() in D:\netcorespace\YueGroup\src\Yuebon.AspNetCore\Mvc\ApiController.cs:line 61
   at Yuebon.WebApi.Areas.Security.Controllers.AppController.GetById(String id) in D:\netcorespace\YueGroup\src\Yuebon.WebApi\Areas\Security\Controllers\AppController.cs:line 44
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[17:12:39.550] Yuebon.AspNetCore.Mvc.Filter.ExceptionHandlingAttribute T76 系统警告信息
Yuebon.AspNetCore.Common.MyApiException: Exception of type 'Yuebon.AspNetCore.Common.MyApiException' was thrown.
   at Yuebon.AspNetCore.Mvc.TokenProvider.ValidateToken(String token) in D:\netcorespace\YueGroup\src\Yuebon.AspNetCore\Mvc\TokenProvider.cs:line 100
   at Yuebon.AspNetCore.Controllers.ApiController.CheckToken() in D:\netcorespace\YueGroup\src\Yuebon.AspNetCore\Mvc\ApiController.cs:line 61
   at Yuebon.WebApi.Areas.Security.Controllers.AppController.GetById(String id) in D:\netcorespace\YueGroup\src\Yuebon.WebApi\Areas\Security\Controllers\AppController.cs:line 44
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[17:20:25.049] Yuebon.AspNetCore.Mvc.Filter.ExceptionHandlingAttribute T20 系统警告信息
Autofac.Core.Registration.ComponentNotRegisteredException: The requested service 'Yuebon.AspNetCore.SSO.SSOAuthHelper' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context)
   at Yuebon.Commons.IoC.IoCContainer.Resolve[T]() in D:\netcorespace\YueGroup\src\Yuebon.Commons\IoC\IoCContainer.cs:line 212
   at Yuebon.WebApi.Areas.SSO.Controllers.CheckController..ctor() in D:\netcorespace\YueGroup\src\Yuebon.WebApi\Areas\SSO\Controllers\CheckController.cs:line 28
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[17:26:02.186] Yuebon.AspNetCore.Mvc.Filter.ExceptionHandlingAttribute T5 系统警告信息
Autofac.Core.Registration.ComponentNotRegisteredException: The requested service 'Yuebon.AspNetCore.SSO.SSOAuthHelper' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context)
   at Yuebon.Commons.IoC.IoCContainer.Resolve[T]() in D:\netcorespace\YueGroup\src\Yuebon.Commons\IoC\IoCContainer.cs:line 212
   at Yuebon.WebApi.Areas.SSO.Controllers.CheckController..ctor() in D:\netcorespace\YueGroup\src\Yuebon.WebApi\Areas\SSO\Controllers\CheckController.cs:line 28
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[17:31:22.401] Yuebon.AspNetCore.Mvc.Filter.ExceptionHandlingAttribute T8 系统警告信息
Microsoft.AspNetCore.Connections.ConnectionResetException: The client has disconnected
 ---> System.Runtime.InteropServices.COMException (0x800704CD): 企图在不存在的网络连接上进行操作。 (0x800704CD)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.IIS.Core.IO.AsyncIOOperation.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadBody()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadAsync(Memory`1 memory, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IIS.Core.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.Pipelines.StreamPipeReader.ReadAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.ModelBinding.FormValueProviderFactory.AddValueProviderAsync(ValueProviderFactoryContext context)
   at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.CreateAsync(ActionContext actionContext, IList`1 factories)
   at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.CreateAsync(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[17:31:57.217] Yuebon.AspNetCore.Mvc.Filter.ExceptionHandlingAttribute T4 系统警告信息
Yuebon.AspNetCore.Common.MyApiException: Exception of type 'Yuebon.AspNetCore.Common.MyApiException' was thrown.
   at Yuebon.AspNetCore.Mvc.TokenProvider.ValidateToken(String token) in D:\netcorespace\YueGroup\src\Yuebon.AspNetCore\Mvc\TokenProvider.cs:line 100
   at Yuebon.AspNetCore.Controllers.ApiController.CheckToken() in D:\netcorespace\YueGroup\src\Yuebon.AspNetCore\Mvc\ApiController.cs:line 61
   at Yuebon.WebApi.Areas.Security.Controllers.AppController.GetById(String id) in D:\netcorespace\YueGroup\src\Yuebon.WebApi\Areas\Security\Controllers\AppController.cs:line 44
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[17:34:58.120] Yuebon.AspNetCore.Mvc.Filter.ExceptionHandlingAttribute T4 系统警告信息
Yuebon.AspNetCore.Common.MyApiException: Exception of type 'Yuebon.AspNetCore.Common.MyApiException' was thrown.
   at Yuebon.AspNetCore.Mvc.TokenProvider.ValidateToken(String token) in D:\netcorespace\YueGroup\src\Yuebon.AspNetCore\Mvc\TokenProvider.cs:line 100
   at Yuebon.AspNetCore.Controllers.ApiController.CheckToken() in D:\netcorespace\YueGroup\src\Yuebon.AspNetCore\Mvc\ApiController.cs:line 61
   at Yuebon.WebApi.Areas.Security.Controllers.AppController.GetById(String id) in D:\netcorespace\YueGroup\src\Yuebon.WebApi\Areas\Security\Controllers\AppController.cs:line 44
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[17:49:04.234] Yuebon.AspNetCore.Mvc.Filter.ExceptionHandlingAttribute T19 系统警告信息
Yuebon.AspNetCore.Common.MyApiException: Exception of type 'Yuebon.AspNetCore.Common.MyApiException' was thrown.
   at Yuebon.AspNetCore.Mvc.TokenProvider.ValidateToken(String token) in D:\netcorespace\YueGroup\src\Yuebon.AspNetCore\Mvc\TokenProvider.cs:line 100
   at Yuebon.AspNetCore.Controllers.ApiController.CheckToken() in D:\netcorespace\YueGroup\src\Yuebon.AspNetCore\Mvc\ApiController.cs:line 61
   at Yuebon.WebApi.Areas.Security.Controllers.AppController.GetById(String id) in D:\netcorespace\YueGroup\src\Yuebon.WebApi\Areas\Security\Controllers\AppController.cs:line 44
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[17:49:19.637] Yuebon.AspNetCore.Mvc.Filter.ExceptionHandlingAttribute T28 系统警告信息
Yuebon.AspNetCore.Common.MyApiException: Exception of type 'Yuebon.AspNetCore.Common.MyApiException' was thrown.
   at Yuebon.AspNetCore.Mvc.TokenProvider.ValidateToken(String token) in D:\netcorespace\YueGroup\src\Yuebon.AspNetCore\Mvc\TokenProvider.cs:line 100
   at Yuebon.AspNetCore.Controllers.ApiController.CheckToken() in D:\netcorespace\YueGroup\src\Yuebon.AspNetCore\Mvc\ApiController.cs:line 61
   at Yuebon.WebApi.Areas.Security.Controllers.AppController.GetById(String id) in D:\netcorespace\YueGroup\src\Yuebon.WebApi\Areas\Security\Controllers\AppController.cs:line 44
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[17:49:39.154] Yuebon.AspNetCore.Mvc.Filter.ExceptionHandlingAttribute T27 系统警告信息
Yuebon.AspNetCore.Common.MyApiException: Exception of type 'Yuebon.AspNetCore.Common.MyApiException' was thrown.
   at Yuebon.AspNetCore.Mvc.TokenProvider.ValidateToken(String token) in D:\netcorespace\YueGroup\src\Yuebon.AspNetCore\Mvc\TokenProvider.cs:line 100
   at Yuebon.AspNetCore.Controllers.ApiController.CheckToken() in D:\netcorespace\YueGroup\src\Yuebon.AspNetCore\Mvc\ApiController.cs:line 61
   at Yuebon.WebApi.Areas.Security.Controllers.AppController.GetById(String id) in D:\netcorespace\YueGroup\src\Yuebon.WebApi\Areas\Security\Controllers\AppController.cs:line 44
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[17:50:17.358] Yuebon.AspNetCore.Mvc.Filter.ExceptionHandlingAttribute T21 系统警告信息
Yuebon.AspNetCore.Common.MyApiException: Exception of type 'Yuebon.AspNetCore.Common.MyApiException' was thrown.
   at Yuebon.AspNetCore.Mvc.TokenProvider.ValidateToken(String token) in D:\netcorespace\YueGroup\src\Yuebon.AspNetCore\Mvc\TokenProvider.cs:line 100
   at Yuebon.AspNetCore.Controllers.ApiController.CheckToken() in D:\netcorespace\YueGroup\src\Yuebon.AspNetCore\Mvc\ApiController.cs:line 61
   at Yuebon.WebApi.Areas.Security.Controllers.AppController.GetById(String id) in D:\netcorespace\YueGroup\src\Yuebon.WebApi\Areas\Security\Controllers\AppController.cs:line 44
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[17:52:12.559] Yuebon.AspNetCore.Mvc.Filter.ExceptionHandlingAttribute T20 系统警告信息
Yuebon.AspNetCore.Common.MyApiException: Exception of type 'Yuebon.AspNetCore.Common.MyApiException' was thrown.
   at Yuebon.AspNetCore.Mvc.TokenProvider.ValidateToken(String token) in D:\netcorespace\YueGroup\src\Yuebon.AspNetCore\Mvc\TokenProvider.cs:line 100
   at Yuebon.AspNetCore.Controllers.ApiController.CheckToken() in D:\netcorespace\YueGroup\src\Yuebon.AspNetCore\Mvc\ApiController.cs:line 61
   at Yuebon.WebApi.Areas.Security.Controllers.AppController.GetById(String id) in D:\netcorespace\YueGroup\src\Yuebon.WebApi\Areas\Security\Controllers\AppController.cs:line 44
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[17:55:46.622] Yuebon.AspNetCore.Mvc.Filter.ExceptionHandlingAttribute T41 系统警告信息
Yuebon.AspNetCore.Common.MyApiException: Exception of type 'Yuebon.AspNetCore.Common.MyApiException' was thrown.
   at Yuebon.AspNetCore.Mvc.TokenProvider.ValidateToken(String token) in D:\netcorespace\YueGroup\src\Yuebon.AspNetCore\Mvc\TokenProvider.cs:line 100
   at Yuebon.AspNetCore.Controllers.ApiController.CheckToken() in D:\netcorespace\YueGroup\src\Yuebon.AspNetCore\Mvc\ApiController.cs:line 61
   at Yuebon.WebApi.Areas.Security.Controllers.AppController.GetById(String id) in D:\netcorespace\YueGroup\src\Yuebon.WebApi\Areas\Security\Controllers\AppController.cs:line 44
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[18:05:18.908] Yuebon.AspNetCore.Mvc.Filter.ExceptionHandlingAttribute T71 系统警告信息
Yuebon.AspNetCore.Common.MyApiException: Exception of type 'Yuebon.AspNetCore.Common.MyApiException' was thrown.
   at Yuebon.AspNetCore.Mvc.TokenProvider.ValidateToken(String token) in D:\netcorespace\YueGroup\src\Yuebon.AspNetCore\Mvc\TokenProvider.cs:line 100
   at Yuebon.AspNetCore.Controllers.ApiController.CheckToken() in D:\netcorespace\YueGroup\src\Yuebon.AspNetCore\Mvc\ApiController.cs:line 61
   at Yuebon.WebApi.Areas.Security.Controllers.AppController.GetById(String id) in D:\netcorespace\YueGroup\src\Yuebon.WebApi\Areas\Security\Controllers\AppController.cs:line 44
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
